language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: Ox0KtYSB/str3L3/X9EV4N3JRcE6NOczMiMdahnHc8QwqKOAiiddCWCD1YiZPbAdLPSDbR8AnWXzmjlVuXZURYEtRUmmCoAk+nbabG8aEGma0qLHJa8A4PFvSf/dSoHIPV8L8OQbYpUnb5Pbl8HmZIJU56TWm8lXJx8tB7FS6dN5Sa5y3ztLjSI4y9AUBW44yGVnX1swyVBL9zNu0OmKiumfTogIn9lQNPrSBoXBaJW0YYAnl7B2Ts0wTATUqsA4AkOzms8Ypo07XHNDbWplpPXzcuQ5JNIBY5nAaHZeeG/AAQcq7JLoO/HEG5A4ZQkI/SMbV6wC2oGv7VtpcUsa67qR0jhgiVXIhLm5Ed6hdePLF0c1vjHwTps0i5jEfmibukq38Bi+YgRKvEahImGabSkEA1iwfRoZQLXQUROE7ubLuDNm+u0MlCZRo2yO3x6IG9p+6UWPUxmjAIqpTy3x7lNw0WT+6c/oaGvsVbgmHJOObexeVgflEK66UPogD1tXwnGkhSq3r6+cvxy9NRG59K2M2UseE7HpEOwTbJRwE0ppln7cy8SuCHAxAFiPxzbL6HEzLFFJqhXR6okFjSz/YQ1pkyEAzSdPCrYRE3UMlJcgKq25j2sDIsrzojKCzN/GxWD8k6gIUCaLIc0ewDDvCxiU7DZtuNdXPzzmanpVr54=
