title: Jekyll AsciiDoc Template
# url: "https://some.site.com"
# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /product
description: The Jekyll AsciiDoc Quickstart project is a leg-up in starting your own website hosted on GitHub with content based in AsciiDoc.

exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

footer: yes
footer_url: "https://github.com/4insyde"
footer_text: "insyde.group"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://www.insyde.group"
 - name: "Test AsciiDoc"
   link: "test-asciidoc"
