# jekyll configuration

title: "Jekyll-asciidoc-quickstart"
highlighter: true

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

# end of configuration
